# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-31 11:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btpproject',
            old_name='description',
            new_name='keywords',
        ),
        migrations.RemoveField(
            model_name='btpproject',
            name='display',
        ),
        migrations.RemoveField(
            model_name='btpproject',
            name='fileuploaded',
        ),
        migrations.RemoveField(
            model_name='btpproject',
            name='isexternal',
        ),
        migrations.RemoveField(
            model_name='btpproject',
            name='isfileuploaded',
        ),
        migrations.RemoveField(
            model_name='btpproject',
            name='postedby',
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 8, 31, 11, 18, 48, 794793, tzinfo=utc)),
        ),
    ]
