# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-04 06:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0002_auto_20160831_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_css', models.TextField()),
                ('admission_year', models.CharField(max_length=4)),
                ('graduate_year', models.CharField(max_length=4)),
                ('btp_start_year', models.CharField(max_length=4)),
                ('btp_end_year', models.CharField(max_length=4)),
                ('honors_start_year', models.CharField(max_length=4)),
                ('honors_end_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 9, 4, 6, 40, 36, 57364, tzinfo=utc)),
        ),
    ]
