# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 06:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('btp', '0003_auto_20160904_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='HonorsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=150)),
                ('keywords', models.TextField(default=b'NA')),
                ('supervisor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HonorsStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=5)),
                ('rollno', models.CharField(max_length=15)),
                ('honorsproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='btp.HonorsProject')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'Batches'},
        ),
        migrations.AlterModelOptions(
            name='btpmarks',
            options={'verbose_name_plural': 'BTPMarks'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.AlterModelOptions(
            name='resources',
            options={'verbose_name_plural': 'Resources'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='area_of_interest',
            field=models.TextField(default=b'Not Provided'),
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 9, 5, 6, 56, 32, 761096, tzinfo=utc)),
        ),
    ]
