# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-06 05:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0004_auto_20160905_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='btpstudent',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='btpstudent',
            name='rollno',
        ),
        migrations.AlterField(
            model_name='btpsetweek',
            name='evalday',
            field=models.DateField(default=datetime.datetime(2016, 9, 6, 5, 12, 16, 264914, tzinfo=utc)),
        ),
    ]
